names = {0: 'object',
 1: 'type',
 2: 'unicode',
 3: 'dict',
 4: 'list',
 5: 'slice',
 6: 'super',
 7: 'staticmethod',
 8: 'float',
 9: 'enumerate',
 10: 'file',
 11: 'basestring',
 12: 'long',
 13: 'tuple',
 14: 'str',
 15: 'property',
 16: 'int',
 17: 'xrange',
 18: 'file',
 19: 'complex',
 20: 'bool',
 21: 'classmethod',
 22: 'function',
 23: 'instancemethod',
 24: 'code',
 25: 'frame',
 26: 'traceback',
 27: 'type'}
checks = [[0,
  1,
  (),
  {'__class__': 'd',
   '__delattr__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__init__': 'm',
   '__new__': 'n',
   '__reduce__': 'm',
   '__reduce_ex__': 'm',
   '__repr__': 'm',
   '__setattr__': 'm',
   '__str__': 'm'}],
 [1,
  1,
  (0,),
  {'__base__': 'd',
   '__bases__': 'd',
   '__basicsize__': 'd',
   '__call__': 'm',
   '__cmp__': 'm',
   '__delattr__': 'm',
   '__dict__': 'd',
   '__dictoffset__': 'd',
   '__doc__': 'd',
   '__flags__': 'd',
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__itemsize__': 'd',
   '__module__': 'd',
   '__mro__': 'd',
   '__name__': 'd',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   '__subclasses__': 'm',
   '__weakrefoffset__': 'd',
   'mro': 'm'}],
 [2,
  1,
  (11,),
  {'__add__': 'm',
   '__cmp__': 'm',
   '__contains__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__getnewargs__': 'm',
   '__getslice__': 'm',
   '__hash__': 'm',
   '__len__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__str__': 'm',
   'capitalize': 'm',
   'center': 'm',
   'count': 'm',
   'encode': 'm',
   'endswith': 'm',
   'expandtabs': 'm',
   'find': 'm',
   'index': 'm',
   'isalnum': 'm',
   'isalpha': 'm',
   'isdecimal': 'm',
   'isdigit': 'm',
   'islower': 'm',
   'isnumeric': 'm',
   'isspace': 'm',
   'istitle': 'm',
   'isupper': 'm',
   'join': 'm',
   'ljust': 'm',
   'lower': 'm',
   'lstrip': 'm',
   'replace': 'm',
   'rfind': 'm',
   'rindex': 'm',
   'rjust': 'm',
   'rstrip': 'm',
   'split': 'm',
   'splitlines': 'm',
   'startswith': 'm',
   'strip': 'm',
   'swapcase': 'm',
   'title': 'm',
   'translate': 'm',
   'upper': 'm',
   'zfill': 'm'}],
 [3,
  1,
  (0,),
  {'__cmp__': 'm',
   '__contains__': 'm',
   '__delitem__': 'm',
   '__doc__': 14,
   '__eq__': 'm',
   '__ge__': 'm',
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__gt__': 'm',
   '__hash__': 'm',
   '__init__': 'm',
   '__iter__': 'm',
   '__le__': 'm',
   '__len__': 'm',
   '__lt__': 'm',
   '__ne__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__setitem__': 'm',
   'clear': 'm',
   'copy': 'm',
   'fromkeys': 21,
   'get': 'm',
   'has_key': 'm',
   'items': 'm',
   'iteritems': 'm',
   'iterkeys': 'm',
   'itervalues': 'm',
   'keys': 'm',
   'pop': 'm',
   'popitem': 'm',
   'setdefault': 'm',
   'update': 'm',
   'values': 'm'}],
 [4,
  1,
  (0,),
  {'__add__': 'm',
   '__contains__': 'm',
   '__delitem__': 'm',
   '__delslice__': 'm',
   '__doc__': 14,
   '__eq__': 'm',
   '__ge__': 'm',
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__getslice__': 'm',
   '__gt__': 'm',
   '__hash__': 'm',
   '__iadd__': 'm',
   '__imul__': 'm',
   '__init__': 'm',
   '__iter__': 'm',
   '__le__': 'm',
   '__len__': 'm',
   '__lt__': 'm',
   '__mul__': 'm',
   '__ne__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__rmul__': 'm',
   '__setitem__': 'm',
   '__setslice__': 'm',
   'append': 'm',
   'count': 'm',
   'extend': 'm',
   'index': 'm',
   'insert': 'm',
   'pop': 'm',
   'remove': 'm',
   'reverse': 'm',
   'sort': 'm'}],
 [5,
  1,
  (0,),
  {'__cmp__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   'indices': 'm',
   'start': 'd',
   'step': 'd',
   'stop': 'd'}],
 [6,
  1,
  (0,),
  {'__doc__': 14,
   '__get__': 'm',
   '__getattribute__': 'm',
   '__init__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__self__': 'd',
   '__self_class__': 'd',
   '__thisclass__': 'd'}],
 [7,
  1,
  (0,),
  {'__doc__': 14,
   '__get__': 'm',
   '__getattribute__': 'm',
   '__init__': 'm',
   '__new__': 'n'}],
 [8,
  1,
  (0,),
  {'__abs__': 'm',
   '__add__': 'm',
   '__cmp__': 'm',
   '__coerce__': 'm',
   '__div__': 'm',
   '__divmod__': 'm',
   '__doc__': 14,
   '__float__': 'm',
   '__floordiv__': 'm',
   '__getattribute__': 'm',
   '__getnewargs__': 'm',
   '__hash__': 'm',
   '__int__': 'm',
   '__long__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__neg__': 'm',
   '__new__': 'n',
   '__nonzero__': 'm',
   '__pos__': 'm',
   '__pow__': 'm',
   '__radd__': 'm',
   '__rdiv__': 'm',
   '__rdivmod__': 'm',
   '__repr__': 'm',
   '__rfloordiv__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__rpow__': 'm',
   '__rsub__': 'm',
   '__rtruediv__': 'm',
   '__str__': 'm',
   '__sub__': 'm',
   '__truediv__': 'm'}],
 [9,
  1,
  (0,),
  {'__doc__': 14,
   '__getattribute__': 'm',
   '__iter__': 'm',
   '__new__': 'n',
   'next': 'm'}],
 [10,
  1,
  (0,),
  {'__delattr__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__init__': 'm',
   '__iter__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   'close': 'm',
   'closed': 'd',
   'encoding': 'd',
   'fileno': 'm',
   'flush': 'm',
   'isatty': 'm',
   'mode': 'd',
   'name': 'd',
   'newlines': 'd',
   'next': 'm',
   'read': 'm',
   'readinto': 'm',
   'readline': 'm',
   'readlines': 'm',
   'seek': 'm',
   'softspace': 'd',
   'tell': 'm',
   'truncate': 'm',
   'write': 'm',
   'writelines': 'm',
   'xreadlines': 'm'}],
 [11, 1, (0,), {'__new__': 'n', '__doc__': 14}],
 [12,
  1,
  (0,),
  {'__abs__': 'm',
   '__add__': 'm',
   '__and__': 'm',
   '__cmp__': 'm',
   '__coerce__': 'm',
   '__div__': 'm',
   '__divmod__': 'm',
   '__doc__': 14,
   '__float__': 'm',
   '__floordiv__': 'm',
   '__getattribute__': 'm',
   '__getnewargs__': 'm',
   '__hash__': 'm',
   '__hex__': 'm',
   '__int__': 'm',
   '__invert__': 'm',
   '__long__': 'm',
   '__lshift__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__neg__': 'm',
   '__new__': 'n',
   '__nonzero__': 'm',
   '__oct__': 'm',
   '__or__': 'm',
   '__pos__': 'm',
   '__pow__': 'm',
   '__radd__': 'm',
   '__rand__': 'm',
   '__rdiv__': 'm',
   '__rdivmod__': 'm',
   '__repr__': 'm',
   '__rfloordiv__': 'm',
   '__rlshift__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__ror__': 'm',
   '__rpow__': 'm',
   '__rrshift__': 'm',
   '__rshift__': 'm',
   '__rsub__': 'm',
   '__rtruediv__': 'm',
   '__rxor__': 'm',
   '__str__': 'm',
   '__sub__': 'm',
   '__truediv__': 'm',
   '__xor__': 'm'}],
 [13,
  1,
  (0,),
  {'__add__': 'm',
   '__contains__': 'm',
   '__doc__': 14,
   '__eq__': 'm',
   '__ge__': 'm',
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__getnewargs__': 'm',
   '__getslice__': 'm',
   '__gt__': 'm',
   '__hash__': 'm',
   '__iter__': 'm',
   '__le__': 'm',
   '__len__': 'm',
   '__lt__': 'm',
   '__mul__': 'm',
   '__ne__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__rmul__': 'm'}],
 [14,
  1,
  (11,),
  {'__add__': 'm',
   '__contains__': 'm',
   '__doc__': 14,
   '__eq__': 'm',
   '__ge__': 'm',
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__getnewargs__': 'm',
   '__getslice__': 'm',
   '__gt__': 'm',
   '__hash__': 'm',
   '__le__': 'm',
   '__len__': 'm',
   '__lt__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__ne__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__str__': 'm',
   'capitalize': 'm',
   'center': 'm',
   'count': 'm',
   'decode': 'm',
   'encode': 'm',
   'endswith': 'm',
   'expandtabs': 'm',
   'find': 'm',
   'index': 'm',
   'isalnum': 'm',
   'isalpha': 'm',
   'isdigit': 'm',
   'islower': 'm',
   'isspace': 'm',
   'istitle': 'm',
   'isupper': 'm',
   'join': 'm',
   'ljust': 'm',
   'lower': 'm',
   'lstrip': 'm',
   'replace': 'm',
   'rfind': 'm',
   'rindex': 'm',
   'rjust': 'm',
   'rstrip': 'm',
   'split': 'm',
   'splitlines': 'm',
   'startswith': 'm',
   'strip': 'm',
   'swapcase': 'm',
   'title': 'm',
   'translate': 'm',
   'upper': 'm',
   'zfill': 'm'}],
 [15,
  1,
  (0,),
  {'__delete__': 'm',
   '__doc__': 'd',
   '__get__': 'm',
   '__getattribute__': 'm',
   '__init__': 'm',
   '__new__': 'n',
   '__set__': 'm',
   'fdel': 'd',
   'fget': 'd',
   'fset': 'd'}],
 [16,
  1,
  (0,),
  {'__abs__': 'm',
   '__add__': 'm',
   '__and__': 'm',
   '__cmp__': 'm',
   '__coerce__': 'm',
   '__div__': 'm',
   '__divmod__': 'm',
   '__doc__': 14,
   '__float__': 'm',
   '__floordiv__': 'm',
   '__getattribute__': 'm',
   '__getnewargs__': 'm',
   '__hash__': 'm',
   '__hex__': 'm',
   '__int__': 'm',
   '__invert__': 'm',
   '__long__': 'm',
   '__lshift__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__neg__': 'm',
   '__new__': 'n',
   '__nonzero__': 'm',
   '__oct__': 'm',
   '__or__': 'm',
   '__pos__': 'm',
   '__pow__': 'm',
   '__radd__': 'm',
   '__rand__': 'm',
   '__rdiv__': 'm',
   '__rdivmod__': 'm',
   '__repr__': 'm',
   '__rfloordiv__': 'm',
   '__rlshift__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__ror__': 'm',
   '__rpow__': 'm',
   '__rrshift__': 'm',
   '__rshift__': 'm',
   '__rsub__': 'm',
   '__rtruediv__': 'm',
   '__rxor__': 'm',
   '__str__': 'm',
   '__sub__': 'm',
   '__truediv__': 'm',
   '__xor__': 'm'}],
 [17,
  1,
  (0,),
  {'__doc__': 14,
   '__getattribute__': 'm',
   '__getitem__': 'm',
   '__iter__': 'm',
   '__len__': 'm',
   '__new__': 'n',
   '__repr__': 'm'}],
 [10,
  1,
  (0,),
  {'__delattr__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__init__': 'm',
   '__iter__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   'close': 'm',
   'closed': 'd',
   'encoding': 'd',
   'fileno': 'm',
   'flush': 'm',
   'isatty': 'm',
   'mode': 'd',
   'name': 'd',
   'newlines': 'd',
   'next': 'm',
   'read': 'm',
   'readinto': 'm',
   'readline': 'm',
   'readlines': 'm',
   'seek': 'm',
   'softspace': 'd',
   'tell': 'm',
   'truncate': 'm',
   'write': 'm',
   'writelines': 'm',
   'xreadlines': 'm'}],
 [19,
  1,
  (0,),
  {'__abs__': 'm',
   '__add__': 'm',
   '__coerce__': 'm',
   '__div__': 'm',
   '__divmod__': 'm',
   '__doc__': 14,
   '__eq__': 'm',
   '__float__': 'm',
   '__floordiv__': 'm',
   '__ge__': 'm',
   '__getattribute__': 'm',
   '__getnewargs__': 'm',
   '__gt__': 'm',
   '__hash__': 'm',
   '__int__': 'm',
   '__le__': 'm',
   '__long__': 'm',
   '__lt__': 'm',
   '__mod__': 'm',
   '__mul__': 'm',
   '__ne__': 'm',
   '__neg__': 'm',
   '__new__': 'n',
   '__nonzero__': 'm',
   '__pos__': 'm',
   '__pow__': 'm',
   '__radd__': 'm',
   '__rdiv__': 'm',
   '__rdivmod__': 'm',
   '__repr__': 'm',
   '__rfloordiv__': 'm',
   '__rmod__': 'm',
   '__rmul__': 'm',
   '__rpow__': 'm',
   '__rsub__': 'm',
   '__rtruediv__': 'm',
   '__str__': 'm',
   '__sub__': 'm',
   '__truediv__': 'm',
   'conjugate': 'm',
   'imag': 'd',
   'real': 'd'}],
 [20,
  1,
  (16,),
  {'__and__': 'm',
   '__doc__': 14,
   '__new__': 'n',
   '__or__': 'm',
   '__rand__': 'm',
   '__repr__': 'm',
   '__ror__': 'm',
   '__rxor__': 'm',
   '__str__': 'm',
   '__xor__': 'm'}],
 [21,
  1,
  (0,),
  {'__doc__': 14,
   '__get__': 'm',
   '__getattribute__': 'm',
   '__init__': 'm',
   '__new__': 'n'}],
 [22,
  1,
  (0,),
  {'__call__': 'm',
   '__delattr__': 'm',
   '__dict__': 'd',
   '__doc__': 'd',
   '__get__': 'm',
   '__getattribute__': 'm',
   '__module__': 'd',
   '__name__': 'd',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   'func_closure': 'd',
   'func_code': 'd',
   'func_defaults': 'd',
   'func_dict': 'd',
   'func_doc': 'd',
   'func_globals': 'd',
   'func_name': 'd'}],
 [23,
  1,
  (0,),
  {'__call__': 'm',
   '__cmp__': 'm',
   '__delattr__': 'm',
   '__doc__': 14,
   '__get__': 'm',
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   'im_class': 'd',
   'im_func': 'd',
   'im_self': 'd'}],
 [24,
  1,
  (0,),
  {'__cmp__': 'm',
   '__doc__': 14,
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__new__': 'n',
   '__repr__': 'm',
   'co_argcount': 'd',
   'co_cellvars': 'd',
   'co_code': 'd',
   'co_consts': 'd',
   'co_filename': 'd',
   'co_firstlineno': 'd',
   'co_flags': 'd',
   'co_freevars': 'd',
   'co_lnotab': 'd',
   'co_name': 'd',
   'co_names': 'd',
   'co_nlocals': 'd',
   'co_stacksize': 'd',
   'co_varnames': 'd'}],
 [25,
  1,
  (0,),
  {'__delattr__': 'm',
   '__doc__': '-',
   '__getattribute__': 'm',
   '__setattr__': 'm',
   'f_back': 'd',
   'f_builtins': 'd',
   'f_code': 'd',
   'f_exc_traceback': 'd',
   'f_exc_type': 'd',
   'f_exc_value': 'd',
   'f_globals': 'd',
   'f_lasti': 'd',
   'f_lineno': 'd',
   'f_locals': 'd',
   'f_restricted': 'd',
   'f_trace': 'd'}],
 [26, 1, (0,), {'__doc__': '-'}],
 [1,
  1,
  (0,),
  {'__base__': 'd',
   '__bases__': 'd',
   '__basicsize__': 'd',
   '__call__': 'm',
   '__cmp__': 'm',
   '__delattr__': 'm',
   '__dict__': 'd',
   '__dictoffset__': 'd',
   '__doc__': 'd',
   '__flags__': 'd',
   '__getattribute__': 'm',
   '__hash__': 'm',
   '__itemsize__': 'd',
   '__module__': 'd',
   '__mro__': 'd',
   '__name__': 'd',
   '__new__': 'n',
   '__repr__': 'm',
   '__setattr__': 'm',
   '__subclasses__': 'm',
   '__weakrefoffset__': 'd',
   'mro': 'm'}]]
print 'comparing with information from 2.3.5'
import make_checker
make_checker.do_check(names, checks)
