# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      asm:
        patterns:
          - "org.ow2.asm:asm*"
      bouncycastle:
        patterns:
          - "org.bouncycastle:bc*"
      jnr:
        patterns:
          - "com.github.jnr:*"
      netty:
        patterns:
          - "io.netty:netty-*"
    ignore:
      - dependency-name: "jline:jline"
