# Copyright © Corporation for National Research Initiatives
include ../../../rules/make.rules
CLASSPATH = ../../..:$(OROMATCHERROOT)

# Uncomment these lines if you do not have the OROMatcher regular
# expression library.

#SKIP = MatchObject.class RegexObject.class re.class
#CLASSES= $(filter-out $(SKIP),$(SOURCES:%.java=%.class))
