# Copyright © Corporation for National Research Initiatives

# Uncomment the following line if you do not have the OROMatcher
# regular expression library.
#
# SKIP = MatchObject.class RegexObject.class re.class

include ../../../rules/make.rules
CLASSPATH = ../../..:$(OROMATCHERROOT)

MD5Module.java: md.class

md.class: md.java
