// Autogenerated AST node
package org.python.parser.ast;
import org.python.parser.SimpleNode;
import java.io.DataOutputStream;
import java.io.IOException;

public interface expr_contextType {
    public static final int Load = 1;
    public static final int Store = 2;
    public static final int Del = 3;
    public static final int AugStore = 4;

    public static final String[] expr_contextTypeNames = new String[] {
        "<undef>",
        "Load",
        "Store",
        "Del",
        "AugStore",
    };
}
