// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.adapter.ListWrapper;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

public class aliasType extends PythonTree {
    public static final PyType TYPE = PyType.fromClass(aliasType.class);
    private String name;
    public String getInternalName() {
        return name;
    }
    @ExposedGet(name = "name")
    public PyObject getName() {
        return Py.None;
    }
    @ExposedSet(name = "name")
    public void setName(Object name) {
        this.name = AstAdapters.to_identifier(name);
    }

    private String asname;
    public String getInternalAsname() {
        return asname;
    }
    @ExposedGet(name = "asname")
    public PyObject getAsname() {
        return Py.None;
    }
    @ExposedSet(name = "asname")
    public void setAsname(Object asname) {
        this.asname = AstAdapters.to_identifier(asname);
    }


    private final static String[] fields = new String[] {"name", "asname"};
    public String[] get_fields() { return fields; }

    public aliasType() {
        this(TYPE);
    }
    public aliasType(PyType subType) {
        super(subType);
    }
    @ExposedNew
    @ExposedMethod
    public void Module___init__(PyObject[] args, String[] keywords) {}
    public aliasType(Object name, Object asname) {
        setName(name);
        setAsname(asname);
    }

    public aliasType(Token token, String name, String asname) {
        super(token);
        this.name = name;
        this.asname = asname;
    }

    public aliasType(Integer ttype, Token token, String name, String asname) {
        super(ttype, token);
        this.name = name;
        this.asname = asname;
    }

    public aliasType(PythonTree tree, String name, String asname) {
        super(tree);
        this.name = name;
        this.asname = asname;
    }

    public String toString() {
        return "alias";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("alias(");
        sb.append("name=");
        sb.append(dumpThis(name));
        sb.append(",");
        sb.append("asname=");
        sb.append(dumpThis(asname));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        traverse(visitor);
        return null;
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
