// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Attribute extends exprType {
    public exprType value;
    public String attr;
    public expr_contextType ctx;

    public static final String[] _fields = new String[] {"value","attr","ctx"};

    public Attribute(Token token, exprType value, String attr, expr_contextType
    ctx) {
        super(token);
        this.value = value;
        this.attr = attr;
        this.ctx = ctx;
    }

    public Attribute(PythonTree tree, exprType value, String attr,
    expr_contextType ctx) {
        super(tree);
        this.value = value;
        this.attr = attr;
        this.ctx = ctx;
    }

    public String toString() {
        return "Attribute";
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitAttribute(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (value != null)
            value.accept(visitor);
    }

public int getLineno() {
    return getLine() + 1;
}

public int getCol_offset() {
    return getCharPositionInLine();
}

}
