// Autogenerated AST node
package org.python.antlr.ast;

import org.python.antlr.AST;
import org.python.core.PyObject;
import org.python.core.PyType;
import org.python.expose.ExposedType;

@ExposedType(name = "_ast.BitAnd", base = PyObject.class)
public class BitAnd extends AST {
    public static final PyType TYPE = PyType.fromClass(BitAnd.class);
    public int asIndex() {
        return asIndex(null);
    }
    public int asIndex(PyObject error) {
        return 10;
    }
}
