// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Break extends stmtType {

    public static final String[] _fields = new String[] {};

    public Break(Token token) {
        super(token);
    }

    public Break(PythonTree tree) {
        super(tree);
    }

    public String toString() {
        return "Break";
    }

}
