// Autogenerated AST node
package org.python.antlr.ast;

import org.python.antlr.AST;

public enum cmpopType {
    UNDEFINED,
    Eq,
    NotEq,
    Lt,
    LtE,
    Gt,
    GtE,
    Is,
    IsNot,
    In,
    NotIn;
    public cmpopType __call__() { return this; }
}
