// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.python.antlr.ListWrapper;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Delete extends stmtType {
    private ListWrapper<exprType> targets;
    public ListWrapper<exprType> getTargets() {
        return targets;
    }
    public void setTargets(java.util.List<exprType> targets) {
        this.targets = new ListWrapper<exprType>(targets);
    }


    private final static String[] fields = new String[] {"targets"};
    public String[] get_fields() { return fields; }

    public Delete(java.util.List<exprType> targets) {
        this.targets = new ListWrapper<exprType>(targets);
        if (targets != null) {
            for(PythonTree t : targets) {
                addChild(t);
            }
        }
    }

    public Delete(Token token, java.util.List<exprType> targets) {
        super(token);
        this.targets = new ListWrapper<exprType>(targets);
        if (targets != null) {
            for(PythonTree t : targets) {
                addChild(t);
            }
        }
    }

    public Delete(int ttype, Token token, java.util.List<exprType> targets) {
        super(ttype, token);
        this.targets = new ListWrapper<exprType>(targets);
        if (targets != null) {
            for(PythonTree t : targets) {
                addChild(t);
            }
        }
    }

    public Delete(PythonTree tree, java.util.List<exprType> targets) {
        super(tree);
        this.targets = new ListWrapper<exprType>(targets);
        if (targets != null) {
            for(PythonTree t : targets) {
                addChild(t);
            }
        }
    }

    public String toString() {
        return "Delete";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Delete(");
        sb.append("targets=");
        sb.append(dumpThis(targets));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitDelete(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (targets != null) {
            for (PythonTree t : targets) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    private int lineno = -1;
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    public void setCol_offset(int num) {
        col_offset = num;
    }

}
