// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Expression extends modType {
    public exprType body;

    public static final String[] _fields = new String[] {"body"};

    public Expression(PythonTree tree, exprType body) {
        super(tree);
        this.body = body;
    }

    public String toString() {
        return "Expression";
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitExpression(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (body != null)
            body.accept(visitor);
    }

}
