// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;

public abstract class exprType extends PythonTree {
    public exprType(Token token) {
        super(token);
    }

    public exprType(PythonTree node) {
        super(node);
    }

}
