// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Expression extends modType {
    public exprType body;

    public static final String[] _fields = new String[] {"body"};

    public Expression(Token token, exprType body) {
        super(token);
        this.body = body;
    }

    public Expression(PythonTree tree, exprType body) {
        super(tree);
        this.body = body;
    }

    public String toString() {
        return "Expression";
    }

}
