// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class keywordType extends PythonTree {
    public String arg;
    public exprType value;

    public static final String[] _fields = new String[] {"arg","value"};

    public keywordType(Token token, String arg, exprType value) {
        super(token);
        this.arg = arg;
        this.value = value;
    }

    public keywordType(PythonTree tree, String arg, exprType value) {
        super(tree);
        this.arg = arg;
        this.value = value;
    }

    public String toString() {
        return "keyword";
    }

}
