// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class List extends exprType implements Context {
    private java.util.List<exprType> elts;
    public java.util.List<exprType> getElts() {
        return elts;
    }
    public void setElts(java.util.List<exprType> elts) {
        this.elts = elts;
    }

    private expr_contextType ctx;
    public expr_contextType getCtx() {
        return ctx;
    }
    public void setCtx(expr_contextType ctx) {
        this.ctx = ctx;
    }


    private final static String[] fields = new String[] {"elts", "ctx"};
    public String[] get_fields() { return fields; }

    public List(java.util.List<exprType> elts, expr_contextType ctx) {
        this.elts = elts;
        if (elts != null) {
            for(PythonTree t : elts) {
                addChild(t);
            }
        }
        this.ctx = ctx;
    }

    public List(Token token, java.util.List<exprType> elts, expr_contextType
    ctx) {
        super(token);
        this.elts = elts;
        if (elts != null) {
            for(PythonTree t : elts) {
                addChild(t);
            }
        }
        this.ctx = ctx;
    }

    public List(int ttype, Token token, java.util.List<exprType> elts,
    expr_contextType ctx) {
        super(ttype, token);
        this.elts = elts;
        if (elts != null) {
            for(PythonTree t : elts) {
                addChild(t);
            }
        }
        this.ctx = ctx;
    }

    public List(PythonTree tree, java.util.List<exprType> elts,
    expr_contextType ctx) {
        super(tree);
        this.elts = elts;
        if (elts != null) {
            for(PythonTree t : elts) {
                addChild(t);
            }
        }
        this.ctx = ctx;
    }

    public String toString() {
        return "List";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("List(");
        sb.append("elts=");
        sb.append(dumpThis(elts));
        sb.append(",");
        sb.append("ctx=");
        sb.append(dumpThis(ctx));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitList(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (elts != null) {
            for (PythonTree t : elts) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    public void setContext(expr_contextType c) {
        this.ctx = c;
    }

    private int lineno = -1;
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    public void setCol_offset(int num) {
        col_offset = num;
    }

}
