// Autogenerated AST node
package org.python.antlr.ast;

import org.python.antlr.AST;

public enum operatorType {
    UNDEFINED,
    Add,
    Sub,
    Mult,
    Div,
    Mod,
    Pow,
    LShift,
    RShift,
    BitOr,
    BitXor,
    BitAnd,
    FloorDiv;
}
