// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Pass extends stmtType {

    public static final String[] _fields = new String[] {};

    public Pass(Token token) {
        super(token);
    }

    public Pass(PythonTree tree) {
        super(tree);
    }

    public String toString() {
        return "Pass";
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitPass(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

}
