// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Return extends stmtType {
    public exprType value;

    public static final String[] _fields = new String[] {"value"};

    public Return(Token token, exprType value) {
        super(token);
        this.value = value;
    }

    public Return(PythonTree tree, exprType value) {
        super(tree);
        this.value = value;
    }

    public String toString() {
        return "Return";
    }

}
