// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.adapter.ListWrapper;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;

@ExposedType(name = "_ast.Str", base = PyObject.class)
public class Str extends exprType {
public static final PyType TYPE = PyType.fromClass(Str.class);
    private Object s;
    public Object getInternalS() {
        return s;
    }
    @ExposedGet(name = "s")
    public PyObject getS() {
        return Py.None;
    }
    @ExposedSet(name = "s")
    public void setS(Object s) {
        this.s = AstAdapters.to_string(s);
    }


    private final static String[] fields = new String[] {"s"};
    public String[] get_fields() { return fields; }

    public Str() {
        this(TYPE);
    }
    public Str(PyType subType) {
        super(subType);
    }
    @ExposedNew
    @ExposedMethod
    public void Module___init__(PyObject[] args, String[] keywords) {}
    public Str(Object s) {
        setS(s);
    }

    public Str(Token token, Object s) {
        super(token);
        this.s = s;
    }

    public Str(Integer ttype, Token token, Object s) {
        super(ttype, token);
        this.s = s;
    }

    public Str(PythonTree tree, Object s) {
        super(tree);
        this.s = s;
    }

    public String toString() {
        return "Str";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Str(");
        sb.append("s=");
        sb.append(dumpThis(s));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitStr(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
    }

    private int lineno = -1;
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    public void setCol_offset(int num) {
        col_offset = num;
    }

}
