// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class TryExcept extends stmtType {
    public stmtType[] body;
    public excepthandlerType[] handlers;
    public stmtType[] orelse;

    public static final String[] _fields = new String[]
    {"body","handlers","orelse"};

    public TryExcept(Token token, stmtType[] body, excepthandlerType[]
    handlers, stmtType[] orelse) {
        super(token);
        this.body = body;
        if (body != null) {
            for(int ibody=0;ibody<body.length;ibody++) {
                addChild(body[ibody]);
            }
        }
        this.handlers = handlers;
        if (handlers != null) {
            for(int ihandlers=0;ihandlers<handlers.length;ihandlers++) {
                addChild(handlers[ihandlers]);
            }
        }
        this.orelse = orelse;
        if (orelse != null) {
            for(int iorelse=0;iorelse<orelse.length;iorelse++) {
                addChild(orelse[iorelse]);
            }
        }
    }

    public TryExcept(int ttype, Token token, stmtType[] body,
    excepthandlerType[] handlers, stmtType[] orelse) {
        super(ttype, token);
        this.body = body;
        if (body != null) {
            for(int ibody=0;ibody<body.length;ibody++) {
                addChild(body[ibody]);
            }
        }
        this.handlers = handlers;
        if (handlers != null) {
            for(int ihandlers=0;ihandlers<handlers.length;ihandlers++) {
                addChild(handlers[ihandlers]);
            }
        }
        this.orelse = orelse;
        if (orelse != null) {
            for(int iorelse=0;iorelse<orelse.length;iorelse++) {
                addChild(orelse[iorelse]);
            }
        }
    }

    public TryExcept(PythonTree tree, stmtType[] body, excepthandlerType[]
    handlers, stmtType[] orelse) {
        super(tree);
        this.body = body;
        if (body != null) {
            for(int ibody=0;ibody<body.length;ibody++) {
                addChild(body[ibody]);
            }
        }
        this.handlers = handlers;
        if (handlers != null) {
            for(int ihandlers=0;ihandlers<handlers.length;ihandlers++) {
                addChild(handlers[ihandlers]);
            }
        }
        this.orelse = orelse;
        if (orelse != null) {
            for(int iorelse=0;iorelse<orelse.length;iorelse++) {
                addChild(orelse[iorelse]);
            }
        }
    }

    public String toString() {
        return "TryExcept";
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitTryExcept(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (body != null) {
            for (int i = 0; i < body.length; i++) {
                if (body[i] != null)
                    body[i].accept(visitor);
            }
        }
        if (handlers != null) {
            for (int i = 0; i < handlers.length; i++) {
                if (handlers[i] != null)
                    handlers[i].accept(visitor);
            }
        }
        if (orelse != null) {
            for (int i = 0; i < orelse.length; i++) {
                if (orelse[i] != null)
                    orelse[i].accept(visitor);
            }
        }
    }

    public int getLineno() {
        return getLine();
    }

    public int getCol_offset() {
        return getCharPositionInLine();
    }

}
