// Autogenerated AST node
package org.python.antlr.ast;

import org.python.antlr.AST;

public enum unaryopType {
    UNDEFINED,
    Invert,
    Not,
    UAdd,
    USub;
    private final static String[] fields = new String[0];
    public String[] get_fields() { return fields; }

    private final static String[] attributes = new String[0];
    public String[] get_attributes() { return attributes; }

    public unaryopType __call__() { return this; }
}
