// Autogenerated AST node
package org.python.antlr.ast;
import org.python.antlr.PythonTree;
import org.antlr.runtime.Token;
import java.io.DataOutputStream;
import java.io.IOException;

public class Yield extends exprType {
    public exprType value;

    public static final String[] _fields = new String[] {"value"};

    public Yield(Token token, exprType value) {
        super(token);
        this.value = value;
    }

    public Yield(PythonTree tree, exprType value) {
        super(tree);
        this.value = value;
    }

    public String toString() {
        return "Yield";
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitYield(this);
    }

    public void traverse(VisitorIF visitor) throws Exception {
        if (value != null)
            value.accept(visitor);
    }

}
