/* Generated By:JJTree&JavaCC: Do not edit this line. PythonGrammarConstants.java */
package org.python.parser;

public interface PythonGrammarConstants {

  int EOF = 0;
  int SPACE = 1;
  int CONTINUATION = 4;
  int NEWLINE1 = 5;
  int NEWLINE = 6;
  int NEWLINE2 = 7;
  int NEWLINE3 = 8;
  int CRLF1 = 12;
  int DEDENT = 14;
  int INDENT = 15;
  int TRAILING_COMMENT = 16;
  int SINGLE_LINE_COMMENT = 17;
  int LPAREN = 18;
  int RPAREN = 19;
  int LBRACE = 20;
  int RBRACE = 21;
  int LBRACKET = 22;
  int RBRACKET = 23;
  int SEMICOLON = 24;
  int COMMA = 25;
  int DOT = 26;
  int COLON = 27;
  int PLUS = 28;
  int MINUS = 29;
  int MULTIPLY = 30;
  int DIVIDE = 31;
  int POWER = 32;
  int LSHIFT = 33;
  int RSHIFT = 34;
  int MODULO = 35;
  int NOT = 36;
  int XOR = 37;
  int OR = 38;
  int AND = 39;
  int EQUAL = 40;
  int GREATER = 41;
  int LESS = 42;
  int EQEQUAL = 43;
  int EQLESS = 44;
  int EQGREATER = 45;
  int LESSGREATER = 46;
  int NOTEQUAL = 47;
  int PLUSEQ = 48;
  int MINUSEQ = 49;
  int MULTIPLYEQ = 50;
  int DIVIDEEQ = 51;
  int MODULOEQ = 52;
  int ANDEQ = 53;
  int OREQ = 54;
  int XOREQ = 55;
  int LSHIFTEQ = 56;
  int RSHIFTEQ = 57;
  int POWEREQ = 58;
  int OR_BOOL = 59;
  int AND_BOOL = 60;
  int NOT_BOOL = 61;
  int IS = 62;
  int IN = 63;
  int LAMBDA = 64;
  int IF = 65;
  int ELSE = 66;
  int ELIF = 67;
  int WHILE = 68;
  int FOR = 69;
  int TRY = 70;
  int EXCEPT = 71;
  int DEF = 72;
  int CLASS = 73;
  int FINALLY = 74;
  int PRINT = 75;
  int PASS = 76;
  int BREAK = 77;
  int CONTINUE = 78;
  int RETURN = 79;
  int IMPORT = 80;
  int FROM = 81;
  int DEL = 82;
  int RAISE = 83;
  int GLOBAL = 84;
  int EXEC = 85;
  int ASSERT = 86;
  int AS = 87;
  int NAME = 88;
  int LETTER = 89;
  int DECNUMBER = 90;
  int HEXNUMBER = 91;
  int OCTNUMBER = 92;
  int FLOAT = 93;
  int EXPONENT = 94;
  int DIGIT = 95;
  int SINGLE_STRING = 100;
  int SINGLE_STRING2 = 101;
  int TRIPLE_STRING = 102;
  int TRIPLE_STRING2 = 103;

  int DEFAULT = 0;
  int FORCE_NEWLINE1 = 1;
  int FORCE_NEWLINE2 = 2;
  int FORCE_NEWLINE = 3;
  int INDENTING = 4;
  int INDENTATION_UNCHANGED = 5;
  int UNREACHABLE = 6;
  int IN_STRING11 = 7;
  int IN_STRING21 = 8;
  int IN_STRING13 = 9;
  int IN_STRING23 = 10;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "<CONTINUATION>",
    "<NEWLINE1>",
    "<NEWLINE>",
    "<NEWLINE2>",
    "<NEWLINE3>",
    "\"\\t\"",
    "\" \"",
    "\"\\f\"",
    "<CRLF1>",
    "\"\"",
    "\"\"",
    "\"<INDENT>\"",
    "<TRAILING_COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"<<\"",
    "\">>\"",
    "\"%\"",
    "\"~\"",
    "\"^\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"**=\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"is\"",
    "\"in\"",
    "\"lambda\"",
    "\"if\"",
    "\"else\"",
    "\"elif\"",
    "\"while\"",
    "\"for\"",
    "\"try\"",
    "\"except\"",
    "\"def\"",
    "\"class\"",
    "\"finally\"",
    "\"print\"",
    "\"pass\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"import\"",
    "\"from\"",
    "\"del\"",
    "\"raise\"",
    "\"global\"",
    "\"exec\"",
    "\"assert\"",
    "\"as\"",
    "<NAME>",
    "<LETTER>",
    "<DECNUMBER>",
    "<HEXNUMBER>",
    "<OCTNUMBER>",
    "<FLOAT>",
    "<EXPONENT>",
    "<DIGIT>",
    "<token of kind 96>",
    "<token of kind 97>",
    "<token of kind 98>",
    "<token of kind 99>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "\"\\\"\\\"\\\"\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 105>",
    "<token of kind 106>",
    "<token of kind 107>",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 111>",
    "<token of kind 112>",
    "\"`\"",
  };

}
