# Run ant regrtest -f verbose.tests on Jython 2.7 on Java versions (GitHub action)

# We expect this to fail (at the time of writing) and the purpose
# is to tell us on which OSes and versions of Java that happens,
# with details.

name: Java versions regrtest 2.7 (verbose tests)

# Only run manually as we don't want to block every PR.
on:
  workflow_dispatch:
    # So we may run on demand (with a chosen file)
   inputs:
     tests_file:
       description: 'File containing the names of tests to run'
       type: string
       required: true
       default: 'verbose.tests'

permissions:
  contents: read

jobs:

  java-versions-regrtest:
    strategy:
      max-parallel: 2
      matrix:
        version: [25, 17]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    continue-on-error: true

    steps:
    - run: echo "Branch ${{ github.ref }} of repository ${{ github.repository }}."
    - run: echo "Java ${{ matrix.version }} on ${{ matrix.os }}."

    # Some tests require Python 2.7 available (not sure it is)
    - name: Install pyenv for choice of Python version.
      # See https://github.com/pyenv/pyenv#installation
      run: |
        curl -sSL https://pyenv.run | bash
        # Manual equivalent of "pyenv init --install".
        # Add to subsequent environments through GITHUB_ variables (files)
        echo "PYENV_ROOT=$HOME/.pyenv" >> "$GITHUB_ENV"
        echo "$HOME/.pyenv/bin" >> "$GITHUB_PATH"
        echo "$HOME/.pyenv/shims" >> "$GITHUB_PATH"

    - name: Check pyenv has taken.
      # See https://github.com/pyenv/pyenv#installation
      run: |
        echo BASH_ENV = "$BASH_ENV"
        echo PYENV_ROOT = "$PYENV_ROOT"
        echo PATH = "$PATH"
        pyenv versions

    - name: Ensure Python 2.7 available
      run: |
        pyenv install 2.7
        pyenv versions
        pyenv global 2.7
        python -V

    # Some tests require exactly-expected line endings
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'

    - name: Developer build with Ant
      run: ant -noinput -buildfile build.xml developer-build

    - name: Specified regression tests with Ant
      run: |
        python -V
        dist/bin/jython -m test.regrtest -v -f ${{ inputs.tests_file }}

