# Run ant regrtest on Jython 2.7 on Java versions (GitHub action)

# We expect this to fail (at the time of writing) and the purpose
# is to tell us on which OSes and versions of Java that happens.

name: Java versions regrtest 2.7

# Only run manually as it takes quite a lot of cpu
on:
  push:
    branches: [ test-java-17-25 ]
  workflow_dispatch:

permissions:
  contents: read

jobs:

  ant-regrtest:
    strategy:
      max-parallel: 2
      matrix:
        version: [17, 25]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 40

    steps:
    - run: echo "Branch ${{ github.ref }} of repository ${{ github.repository }}."
    - run: echo "Java ${{ matrix.version }} on ${{ matrix.os }}."

    # Some tests require exactly-expected line endings
    - run: git config --global core.autocrlf input

    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.version }}
        distribution: 'temurin'

    - name: Regression test with Ant
      run: ant -noinput -buildfile build.xml regrtest-ci

